config {
    type: "incremental",
    schema: "ankit_statging",
    uniqueKey: ["MBLNR", "MJAHR", "ZEILE", "BSTAUS"],
    tags: ["03bf_execution"]

}

SELECT
  *,
  PARSE_DATE('%Y%m%d', SUBSTR(file_id, 11, 8)) AS extracted_date
FROM
  ${ref("03bfD")}
${when(incremental(), 
  `WHERE PARSE_DATE('%Y%m%d', SUBSTR(file_id, 11, 8)) > (
    SELECT MAX(PARSE_DATE('%Y%m%d', SUBSTR(file_id, 11, 8)))
    FROM ${ref('03bf_bak')}
  )`
)}